version: '2'
services:
  weblate:
    build: .
    links:
      - cache
    ports:
      - 8001:8080
    volumes:
      - ./data/weblate:/app/data
    env_file:
      - ./environment
    restart: unless-stopped
    depends_on:
      - cache
  cache:
    image: redis:4-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./data/redis:/data
