#!/bin/python
import subprocess

REPOSITORIES = [
    ('druidoo-addons', '12.0'),
]

for repo, branch in REPOSITORIES:
    subprocess.check_call([
        '/usr/local/bin/wocg-create-project',
        '--repository', 'https://github.com/druidoo/' + repo,
        '--branch', branch,
        '--tmpl-component-slug', '0-druidoo-project-template-addon',
    ])

subprocess.check_call([
    '/usr/local/bin/wocg-create-components',
])
